apiVersion: v1
kind: Pod
metadata:
  name: testpod
  namespace: test-ns
  labels:
    team: devops
spec:
  containers:
  - name: containername
    image: saipraneeth8188/nodejs:1
    ports:
    - containerPort: 9981
---

apiVersion: v1
kind: Service
metadata:
  name: secondcontainer
  namespace: test-ns
spec:
  type: NodePort
  selector:
    team: devops
  ports:
  - port: 80
    targetPort: 9981


