apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nameofthedaemonset
  namespace: test-ns
  labels:
    app: DaemonSetapp
spec:
  selector:
    matchLabels:
      team: saiTeam
  template:
    metadata:
      name: podname
      labels:
        team: saiTeam
    spec:
      containers:
      - name: nameofthecontainer
        image: saipraneeth8188/saidocker:1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: servicefordaemonset
  namespace: test-ns
spec:
  selector:
    team: saiTeam
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  

