apiVersion: v1
kind: Pod
metadata:
  name: testingpod
  labels:
    team: saiteam
spec:
  containers:
  - name: container1
    image: saipraneeth8188/saidocker:1
    ports:
    - containerPort: 8080
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: testsvc
spec:
  selector:
    team: saiteam
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: maven
  - port: 80
    targetPort: 80
    name: nginx




