apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa
  labels:
    app: hpa-example
spec:
  replicas: 2
  selector:
    matchLabels:
      team: saiTeam
  template:
    metadata:
      name: saipod
      labels:
        team: saiTeam
    spec:
      containers:
      - name: nameofthecontainer
        image: k8s.gcr.io/hpa-example
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "100m"
            memory: "1Gi"

---

apiVersion: v1
kind: Service
metadata:
  name: servicenameforhpa
spec:
  type: NodePort
  selector:
    team: saiTeam
  ports:
  - port: 80
    targetPort: 80
