apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      name: podname
      labels:
        app: jenkins
    spec:
      volumes:
      - name: jenkinsvol
        persistentVolumeClaim:
          claimName: jenkinspvc
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "0.5"
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 1Gi
        volumeMounts:
        - name: jenkinsvol
          mountPath: /var/jenkins_home


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkinspvc
spec:
  resources:
    requests:
      storage: "1Gi"
  accessModes:
  - ReadWriteOnce
---

apiVersion: v1
kind: Service
metadata:
  name: servicename
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30009

