apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicasetname
  namespace: test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      name: podname
      labels:
        app: nodeapp
    spec:
      containers:
      - name: containername
        image: saipraneeth8188/saidocker:1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: serviceforreplicaset
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
  - port: 80
    targetPort: 8080

