---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    team: devteam
  namespace: test-ns
spec:
  containers:
  - name: containername
    image: saipraneeth8188/saidocker:1
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1
        memory: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: servicename
  namespace: test-ns
spec:
  type: NodePort
  selector:
    team: devteam
  ports:
    - port: 80
      targetPort: 8080

